name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)" >> python__${{matrix.python-version}}.txt
      - name: Accidentally upload to the same artifact via multiple jobs
        uses: actions/upload-artifact@v3
        with:
          name: my-python
          path: ${{ github.workspace }}
